name: Build & Publish Docker Image

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Se connecter au registry GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # 3. Build et push
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .               # dossier du Dockerfile
          push: true               # push après build
          tags: |
            ghcr.io/${{ secrets.REGISTRY_USER }}/siteweb:latest
            ghcr.io/${{ secrets.REGISTRY_USER }}/siteweb:${{ github.sha }}
