name: Builder la Franquette
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: get the code 
        uses: actions/checkout@v4
      - name: setup node 
        uses: actions/setup-node@v4
        with:
          node_version: 18
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build 
      - name: get the dist file into an artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: la-bonne-franquette
          path: ./dist