name: Builder la Franquette
on: [workflow_dispatch]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node_version: 18
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: get the dist file into an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./dist
  deploy:
    needs: build_vue

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4